// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {


  public static final double intakespeed = 1.0;
  public static final double drivespeed = 1.0;
  public static final double driverotatespeed = 0.9;
  public static final double shootspeed = 1.0;
  public static final double climbspeed = 1.0;
  
   
    public static final class DriveConstants {
       public static final int kLeftMotor1Port = 0;
       public static final int kLeftMotor2Port = 1;
       public static final int kRightMotor1Port = 2;
       public static final int kRightMotor2Port = 3; 
     }
     public static final class eleConstants {
      public static final int kMotor1Port = 4;
       
     }

     public static final class ClimberConstants {
      public static final int kMotor1Port = 5;
      public static final int kMotor2Port = 6;
     }
     public static final class intakeConstants {
      public static final int kMotor1Port = 7;
     
     }
public static final class ClimberCatcherConstants{
public static final int kMotor1Port = 9 ;///catcher CAN #

}

     public static final class HDriveConstants {
      public static final int kMotor1Port = 8;
     }
     


}

