// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.ele;

public class Ele_Run_Both extends CommandBase {
  private final ele m_ele;
    private double m_my_set1_point;
    private double m_my_set2_point;

  /** Creates a new Ele_Run_Both. */
  public Ele_Run_Both(double my_set1_point, double my_set2_point, ele subsystem) {
    // Use addRequirements() here to declare subsystem dependencies.
    m_my_set1_point = my_set1_point;
    m_my_set2_point = my_set2_point;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_ele = subsystem;
        addRequirements(m_ele);
  }

  // Called when the command is initially scheduled.
  @Override
  public void initialize() {}

  // Called every time the scheduler runs while the command is scheduled.
  @Override
  public void execute() {
    m_ele.my_set_ele_Motor1_speed(m_my_set1_point);
    m_ele.my_set_ele_Motor2_speed(m_my_set2_point);
  }

  // Called once the command ends or is interrupted.
  @Override
  public void end(boolean interrupted) {
    m_ele.my_set_ele_Motor1_speed(0);
    m_ele.my_set_ele_Motor2_speed(0);
  }

  // Returns true when the command should end.
  @Override
  public boolean isFinished() {
    return false;
  }
}
